### ISSUE TITLE
there is an error when I restart my idea 2017

### ISSUE THREAD

**Issue by songxianpeng** [halirutan/IntelliJ-Key-Promoter#7]
2017-07-16 21:24:39,974 [   5042]   INFO - j.ide.script.IdeStartupScripts - 0 startup script(s) found 
2017-07-16 21:24:40,081 [   5149]  ERROR - llij.ide.plugins.PluginManager - com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing plugin Key Promoter X 
java.lang.RuntimeException: com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing plugin Key Promoter X
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:210)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.idea.MainImpl$1$1.a(MainImpl.java:63)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:343)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing plugin Key Promoter X
	at com.intellij.ide.plugins.PluginManager.handleComponentError(PluginManager.java:254)
	at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.handleInitComponentError(PlatformComponentManagerImpl.java:43)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:509)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:120)
	at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:466)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:473)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:104)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:425)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:411)
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:203)
	... 20 more
Caused by: com.intellij.diagnostic.PluginException:  [Plugin: Key Promoter X]
	... 35 more
Caused by: java.lang.AssertionError
	at com.intellij.util.xmlb.MapBinding.deserializeKeyOrValue(MapBinding.java:195)
	at com.intellij.util.xmlb.MapBinding.deserialize(MapBinding.java:160)
	at com.intellij.util.xmlb.MapBinding.deserializeList(MapBinding.java:124)
	at com.intellij.util.xmlb.Binding.deserializeList(Binding.java:54)
	at com.intellij.util.xmlb.OptionTagBinding.deserialize(OptionTagBinding.java:103)
	at com.intellij.util.xmlb.BasePrimitiveBinding.deserializeUnsafe(BasePrimitiveBinding.java:66)
	at com.intellij.util.xmlb.BeanBinding.deserializeInto(BeanBinding.java:234)
	at com.intellij.util.xmlb.BeanBinding.deserializeInto(BeanBinding.java:188)
	at com.intellij.util.xmlb.BeanBinding.deserialize(BeanBinding.java:138)
	at com.intellij.util.xmlb.XmlSerializer.deserialize(XmlSerializer.java:68)
	at com.intellij.openapi.components.impl.stores.DefaultStateSerializer.deserializeState(DefaultStateSerializer.java:53)
	at com.intellij.configurationStore.StateStorageBase.deserializeState(StateStorageBase.kt:43)
	at com.intellij.configurationStore.StateGetter.getState(StorageBaseEx.kt:43)
	at com.intellij.configurationStore.ComponentStoreImpl.a(ComponentStoreImpl.kt:332)
	at com.intellij.configurationStore.ComponentStoreImpl.a(ComponentStoreImpl.kt:292)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:92)
	at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.initializeComponent(PlatformComponentManagerImpl.java:54)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:233)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:239)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:206)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:48)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:38)
	at de.halirutan.keypromoterx.KeyPromoter.<init>(KeyPromoter.java:46)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:103)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:80)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:63)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:468)
	... 32 more

**Comment by halirutan** [comment]
It looks like the `KeyPromoterStatistic.xml` file is not in the required format. This is my fault as I have changed the format for Key Promoter X without changing the file ~format~ name. Can you please try the following:

1. Ensure that you have **either** *Key Promoter* **or** *Key Promoter X* installed
2. Remove the statistics file by
    1. Go in IDEA to Help -> Show Log in File Manager. This gives for me the logfile under `/home/patrick/.IdeaIC2017.1/system/log/`
    2. Close IDEA
    3. Navigate to the equivalent folder on your machine `/home/patrick/.IdeaIC2017.1/config/options/` and delete the file `KeyPromoterStatistic.xml`
    4. Restart IDEA

**Comment by songxianpeng** [comment]
@halirutan that's help,thanks a lot :D

**Comment by songxianpeng** [comment]
_the issue came out again after I restart my computer and my idea.here is the content of idea.log ._


2017-07-17 22:30:48,223 [   2625]   INFO - llij.ide.plugins.PluginManager - Loaded bundled plugins: ASP (0.1), Ant Support (1.0), Application Servers View (0.2.0), AspectJ Support (1.2), Bytecode Viewer (0.1), CFML Support (3.53), CSS Support (171.4694.70), CVS Integration (11), ClearCase Integration (2.0), CoffeeScript (2.0), Copyright (8.1), Coverage (171.4694.70), Cucumber for Groovy (999.999), Cucumber for Java (999.999), DSM Analysis (1.0.0), Database Tools and SQL (1.0), Eclipse Integration (3.0), EditorConfig (171.4694.70), Emma (171.4694.70), Flash/Flex Support (171.4694.70), FreeMarker support (1.0), GWT Support (1.0), Geronimo Integration (1.0), Gherkin (999.999), Git Integration (8.1), GitHub (171.4694.70), GlassFish Integration (1.0), Google App Engine Integration (1.1.4), Gradle (171.4694.70), Grails (9.0), Groovy (9.0), Guice (8.0), HTML Tools (2.0), Haml (171.4694.70), Hibernate Support (1.0), I18n for Java (171.4694.70), IDEA CORE (171.4694.70), IntelliLang (8.0), J2ME (1.0), JBA Cloud Config (171.4694.70), JBoss Arquillian Support (1.0), JBoss Drools Support (1.0), JBoss Integration (1.0), JBoss Seam Pageflow Support (1.0), JBoss Seam Pages Support (1.0), JBoss Seam Support (1.0), JBoss Support (1.0), JBoss jBPM (2.0.0), JSR45 Integration (1.0), JUnit (1.0), Java Bytecode Decompiler (171.4694.70), Java EE: Batch Applications (1.0), Java EE: Bean Validation Support (1.1), Java EE: Contexts and Dependency Injection (1.1), Java EE: EJB, JPA, Servlets (1.0), Java EE: JMS, JSON Processing, Concurrency, Transaction  (1.0), Java EE: Java Server Faces (2.2.X.), Java EE: RESTful Web Services (JAX-RS) (1.0), Java EE: Web Services (JAX-WS) (1.9), Java EE: WebSockets (1.0), Java Server Pages (JSP) Integration (1.0), JavaFX (1.0), JavaScript Debugger (1.0), JavaScript Intention Power Pack (0.9.4), JavaScript Support (1.0), Jetty Integration (1.0), Kotlin (1.1.2-release-IJ2017.1-1), Less support (171.4694.70), Markdown support (VERSION), Maven Integration (171.4694.70), Maven Integration Extension (171.4694.70), Osmorc (1.4.9), Perforce Integration (2.0), Persistence Frameworks Support (1.0), Playframework Support (1.0), Plugin DevKit (1.0), Properties Support (171.4694.70), QuirksMode (171.4694.70), REST Client (171.4694.70), Refactor-X (2.01), Remote Hosts Access (0.1), Resin Integration (8.1), SSH Remote Run (0.1), Sass support (171.4694.70), Settings Repository (171.4694.70), Spring AOP/@AspectJ (1.0), Spring Batch (1.0), Spring Boot (1.0), Spring Data (1.0), Spring Integration Patterns (1.0), Spring MVC (1.0), Spring OSGi (1.0), Spring Security (1.0), Spring Support (1.0), Spring Web Flow (1.0), Spring Web Services (1.0), Spring WebSocket (1.0), Spy-js (171.4694.70), Struts 1.x (2.0), Struts 2 (1.0), Stylus support (999.999), Subversion Integration (1.1), TFS Integration (999.999), Tapestry support (1.0), Task Management (1.0), Terminal (0.1), TestNG-J (8.0), Thymeleaf (1.0), Time Tracking (1.0), Tomcat and TomEE Integration (1.0), UI Designer (171.4694.70), UML Support (1.0), Vaadin Support (1.0), Velocity support (1.0), W3C Validators (2.0), WebLogic Integration (1.0), WebSphere Integration (1.0), XPathView + XSLT Support (4), XSLT-Debugger (1.4), YAML (171.4694.70), ZKM-Unscramble (1.0), dmServer Support (0.9.5), hg4idea (10.0), tslint (171.4694.70) 
2017-07-17 22:30:48,223 [   2625]   INFO - llij.ide.plugins.PluginManager - Loaded custom plugins: .ignore (1.7.6), 360 FireLine Plugin (1.2.8), BashSupport (1.6.10.171), CMD Support (1.0.5), CodeGlance (1.5.2), FindBugs-IDEA (1.0.1), Ini4Idea (171.3780.104), JRebel for IntelliJ (7.0.12), Key Promoter X (5.5), LiveEdit (171.4694.29), MyBatis plugin (2.92) 
2017-07-17 22:30:48,223 [   2625]   INFO - llij.ide.plugins.PluginManager - Disabled plugins: Android Support (10.2.2.2), Cloud Foundry integration (1.0), CloudBees integration (1.0), Heroku integration (1.0), OpenShift integration (1.0) 
2017-07-17 22:30:49,621 [   4023]   INFO - cloudConfig.CloudConfigManager - === Offline: (null) false === 
2017-07-17 22:30:49,669 [   4071]   INFO - ellij.util.io.PagedFileStorage - lower=100; upper=500; buffer=10; max=705 
2017-07-17 22:30:49,856 [   4258]   INFO - pl.local.NativeFileWatcherImpl - Starting file watcher: D:\Work\Software\Editor\IntelliJIDEA\bin\fsnotifier64.exe 
2017-07-17 22:30:49,892 [   4294]   INFO - pl.local.NativeFileWatcherImpl - Native file watcher is operational. 
2017-07-17 22:30:50,827 [   5229]   INFO - com.intellij.ide.ui.UISettings - Loaded: fontSize=12, fontScale=0.0; restored: fontSize=12, fontScale=1.0 
2017-07-17 22:30:51,517 [   5919]   INFO - til.net.ssl.CertificateManager - Default SSL context initialized 
2017-07-17 22:30:51,543 [   5945]   INFO - rains.ide.BuiltInServerManager - built-in server started, port 63342 
2017-07-17 22:30:51,577 [   5979]   INFO - gs.impl.UpdateCheckerComponent - channel: release 
2017-07-17 22:30:51,916 [   6318]   INFO - il.indexing.FileBasedIndexImpl - Index exts enumerated:288 
2017-07-17 22:30:51,923 [   6325]   INFO - il.indexing.FileBasedIndexImpl - Index scheduled:5 
2017-07-17 22:30:51,978 [   6380]   INFO - tellij.psi.stubs.StubIndexImpl - All stub exts enumerated:49 
2017-07-17 22:30:51,979 [   6381]   INFO - tellij.psi.stubs.StubIndexImpl - stub exts update scheduled:1 
2017-07-17 22:30:52,135 [   6537]   INFO - j.ide.script.IdeStartupScripts - 0 startup script(s) found 
2017-07-17 22:30:52,267 [   6669]  ERROR - llij.ide.plugins.PluginManager - com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing plugin Key Promoter X 
java.lang.RuntimeException: com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing plugin Key Promoter X
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:210)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.idea.MainImpl$1$1.a(MainImpl.java:63)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:343)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing plugin Key Promoter X
	at com.intellij.ide.plugins.PluginManager.handleComponentError(PluginManager.java:254)
	at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.handleInitComponentError(PlatformComponentManagerImpl.java:43)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:509)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:120)
	at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:466)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:473)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:104)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:425)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:411)
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:203)
	... 20 more
Caused by: com.intellij.diagnostic.PluginException:  [Plugin: Key Promoter X]
	... 35 more
Caused by: java.lang.AssertionError
	at com.intellij.util.xmlb.MapBinding.deserializeKeyOrValue(MapBinding.java:195)
	at com.intellij.util.xmlb.MapBinding.deserialize(MapBinding.java:160)
	at com.intellij.util.xmlb.MapBinding.deserializeList(MapBinding.java:124)
	at com.intellij.util.xmlb.Binding.deserializeList(Binding.java:54)
	at com.intellij.util.xmlb.OptionTagBinding.deserialize(OptionTagBinding.java:103)
	at com.intellij.util.xmlb.BasePrimitiveBinding.deserializeUnsafe(BasePrimitiveBinding.java:66)
	at com.intellij.util.xmlb.BeanBinding.deserializeInto(BeanBinding.java:234)
	at com.intellij.util.xmlb.BeanBinding.deserializeInto(BeanBinding.java:188)
	at com.intellij.util.xmlb.BeanBinding.deserialize(BeanBinding.java:138)
	at com.intellij.util.xmlb.XmlSerializer.deserialize(XmlSerializer.java:68)
	at com.intellij.openapi.components.impl.stores.DefaultStateSerializer.deserializeState(DefaultStateSerializer.java:53)
	at com.intellij.configurationStore.StateStorageBase.deserializeState(StateStorageBase.kt:43)
	at com.intellij.configurationStore.StateGetter.getState(StorageBaseEx.kt:43)
	at com.intellij.configurationStore.ComponentStoreImpl.a(ComponentStoreImpl.kt:332)
	at com.intellij.configurationStore.ComponentStoreImpl.a(ComponentStoreImpl.kt:292)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:92)
	at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.initializeComponent(PlatformComponentManagerImpl.java:54)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:233)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:239)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:206)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:48)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:38)
	at de.halirutan.keypromoterx.KeyPromoter.<init>(KeyPromoter.java:46)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:103)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:80)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:63)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:468)
	... 32 more
2017-07-17 22:30:52,271 [   6673]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 2017.1.5  Build #IU-171.4694.70 
2017-07-17 22:30:52,271 [   6673]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.8.0_112-release 
2017-07-17 22:30:52,271 [   6673]  ERROR - llij.ide.plugins.PluginManager - VM: OpenJDK 64-Bit Server VM 
2017-07-17 22:30:52,271 [   6673]  ERROR - llij.ide.plugins.PluginManager - Vendor: JetBrains s.r.o 
2017-07-17 22:30:52,271 [   6673]  ERROR - llij.ide.plugins.PluginManager - OS: Windows 10 
2017-07-17 22:30:53,863 [   8265]   INFO - pl$FileIndexDataInitialization - Initialization done:1939 
2017-07-17 22:30:54,091 [   8493]   INFO - com.intellij.ide.ui.UISettings - Loaded: fontSize=12, fontScale=1.0; restored: fontSize=12, fontScale=1.0 
2017-07-17 22:30:54,092 [   8494]   INFO - com.intellij.ide.ui.UISettings - Loaded: fontSize=12, fontScale=1.0; restored: fontSize=12, fontScale=1.0 
2017-07-17 22:30:54,312 [   8714]   INFO - .openapi.application.Preloader - Finished preloading com.intellij.openapi.actionSystem.impl.ActionPreloader@4e37a22e 
2017-07-17 22:30:55,020 [   9422]   INFO - exImpl$StubIndexInitialization - Initialization done:1156 
2017-07-17 22:30:55,778 [  10180]   INFO - bugs.resources.ResourcesLoader - Loading locale properties for 'zh_CN) 
2017-07-17 22:30:55,801 [  10203]   INFO - .openapi.application.Preloader - Finished preloading com.intellij.ide.ui.search.SearchableOptionPreloader@75c46296 
2017-07-17 22:30:56,228 [  10630]   INFO - .openapi.application.Preloader - Finished preloading com.intellij.codeInsight.completion.CompletionPreloader@152145e3

**Comment by halirutan** [comment]
@xpressSong Hmm, it is the same error. The important part is

```
at de.halirutan.keypromoterx.KeyPromoter.(KeyPromoter.java:46)
```

which is exactly the place where the [Key Promoter X statistics](https://github.com/halirutan/IntelliJ-Key-Promoter/blob/KeyPromoterX/src/de/halirutan/keypromoterx/KeyPromoter.java#L46) are accessed. 

Question: Are you 100% sure, that you **don't** have the original Key Promoter (the one without X) installed?

**Edit:** I have pushed a new [release version here](https://github.com/halirutan/IntelliJ-Key-Promoter/releases/tag/v5.6) where I use a unique `KeyPromoterXStatistic.xml`file that shouldn't clash with other files. I would really like to find the source of your error first and I'm almost sure that an older plugin is overwriting the statistics file which is then invalid for the current version of Key Promoter X.

That being said, can you check (again using the base directory that you get when you use Help -> Show Log in File Manager) the contents of your plugin folder? It islocated under your equivalent of

```
/home/patrick/.IdeaIC2017.1/config/plugins/
```

There should be only one directory `Key Promoter X` and no other directory that is called something with Key Promoter. Additionally, what version of Key Promoter X are you using? You see it in Settings -> Plugins -> Key Promoter X.

If we don't find the reason for your error, can you remove all Key Promoter plugins you have installed, download the version 5.6 zip from the link above and use Settings -> Plugins -> Install from Disk and look if it solves your problem.

**Comment by songxianpeng** [comment]
@halirutan yes I'm sure.I have delete all config and files under

>  .IntelliJIdea2017.2\config\plugins\

 and 

> .IntelliJIdea2017.2\config\options\

 I just reinstall my key prompter X and modified my key prompter X settings ,and then restart my idea,it's worked well, after about 2 hours I restart my idea,the error occured again...

I have modified my shortcut suggest number to 0,No other changes

![image](https://user-images.githubusercontent.com/9303424/28350115-49731866-6c79-11e7-97cc-2a45c0b4754e.png)


thanks for help.

**Comment by halirutan** [comment]
@xpressSong After the error occurs, can you put the contents of `KeyPromoterStatistic.xml` to pastebin and link it here? I'm absolutely stunned since this error did not occur for anyone else. Additionally, what operating system are you using? From your config folder I assume you are using Ultimate?

**Comment by songxianpeng** [comment]
@halirutan  I'm using windows 10,idea 2017.1,and I update my idea ultimate  to 2017.2 this morning.

I reinstall my key prompter X and I woud upload the settings file the next time error occurs.

**Comment by halirutan** [comment]
@xpressSong Thanks.

**Comment by songxianpeng** [comment]
The issue didn't appear again. Even though I'm really confused with it，but I think I should close this issue. And thank you very much.@halirutan
